#!/usr/bin/env bash
#
# Slice the dns-01 orphan-reap table out of the shipped
# ../../../src/ngx_autocert_order.c into generated_orphan.inc, compiled by
# ci/tests/unit/test_orphan_reap.c.
#
# Why slice, not include-shim the whole .c: ngx_autocert_order.c is the ACME
# order state machine and pulls in the account POST primitive, the JSON
# parser, the challenge/ALPN shm zones, OpenSSL X509/PEM and the nginx event
# loop -- far too much to stand up for one pid table. The table itself depends
# only on <signal.h>, <sys/wait.h> and ngx_str/ngx_log declarations, so the
# region is lifted verbatim and stays locked to production code with no copy
# drift.
#
# The slice is anchored on exact production lines: from the
# NGX_AUTOCERT_ORPHAN_MAX #define through the end of
# ngx_autocert_orphan_reap(), which covers the entry struct, the table, the
# injectable-waitpid typedef, _reset(), _add() and _reap(). The arm/timer
# handler below it are NOT sliced -- they need a live nginx event loop and are
# out of this TU's reach (stated in the test header too).

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_order.c"
OUT="$DIR/generated_orphan.inc"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

start=$(grep -nE '^#define NGX_AUTOCERT_ORPHAN_MAX' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
	echo "✗ could not locate NGX_AUTOCERT_ORPHAN_MAX in $SRC" >&2
	exit 1
fi

# Extract the function. Captured into a variable rather than redirected into
# $OUT inside a block: shellcheck's SC2094 fires (info, and CI gates on info)
# whenever a block that writes $OUT also mentions it, even in an error branch.
if ! body=$(awk -v s="$start" '
        NR >= s {
            print
            if ($0 ~ /^ngx_autocert_orphan_reap\(/) { entered = 1 }
            # Count braces once the body is open. The function ends when depth
            # returns to zero -- NOT at "the next lone } in column 1", which is
            # also the terminator of the NEXT function if this one was
            # reformatted. Measured: with that reformat, a lone-} rule silently
            # emitted more than needed, swallowing the following function, and
            # still exited 0.
            if (entered) {
                n = gsub(/{/, "{"); depth += n
                n = gsub(/}/, "}"); depth -= n
                if (opened && depth == 0) { closed = 1; exit }
                if (depth > 0) { opened = 1 }
            }
        }
        END { if (!closed) exit 1 }
    ' "$SRC"); then
	echo "✗ ngx_autocert_orphan_reap() body never closed at brace depth 0 in $SRC (reformatted?)" >&2
	rm -f "$OUT"
	exit 1
fi

{
	echo "/* --- dns-01 orphan-reap table sliced from ngx_autocert_order.c --- */"
	echo "/* Generated by ci/tests/unit/extract_orphan.sh — do not edit by hand. */"
	printf '%s\n' "$body"
} >"$OUT"

for sym in NGX_AUTOCERT_ORPHAN_MAX ngx_autocert_orphan_add ngx_autocert_orphan_reap ngx_autocert_orphans_reset; do
	if ! grep -q "$sym" "$OUT"; then
		echo "✗ $sym missing from generated output (source layout changed?)" >&2
		rm -f "$OUT"
		exit 1
	fi
done

echo "✓ extracted dns-01 orphan-reap table -> $OUT"
