#!/usr/bin/env bash
#
# Slice the off-event-loop RSA keygen slot out of the shipped
# ../../../src/ngx_autocert_order.c into generated_keygen.inc, compiled by
# ci/tests/unit/test_keygen_offload.c.
#
# Why slice, not include-shim the whole .c: ngx_autocert_order.c is the ACME
# order state machine -- account POST, JSON parser, challenge/ALPN shm zones,
# OpenSSL X509/PEM and a live nginx event loop. The keygen slot itself touches
# only EVP_PKEY, ngx_thread_task_t and ngx_str/ngx_log declarations, so the
# region is lifted verbatim and stays locked to production code with no copy
# drift.
#
# What the slice carries -- the whole cancellation state machine, which is the
# part with a use-after-free hazard in it:
#
#   ngx_autocert_keygen_is_rsa()     which key types are offloaded at all
#   ngx_autocert_keygen_t            the process-lifetime slot
#   ngx_autocert_keygen_abandon()    detach on order_free()
#   ngx_autocert_keygen_thread()     the worker-thread body
#   ngx_autocert_keygen_completion() the event-loop resume/cleanup decision
#   ngx_autocert_keygen_inline()     the shared degraded-path fallback
#   ngx_autocert_keygen_post()       pool lookup, task reuse and EVERY degraded
#                                    path (no pool / busy slot / post failure)
#
# The test does NOT re-implement any of that: it drives the SHIPPED functions
# directly, so an ownership bug introduced in order.c (freeing into a dead
# order, leaking the key on the abandoned path, releasing the slot too late,
# wedging the cached task after a failed post) fails this suite.
#
# _post() reaches the outside world through four symbols --
# ngx_thread_pool_get(), ngx_thread_task_post(), ngx_cycle and ngx_alloc().
# The test TU supplies the first THREE, the same injection seam the orphan-reap
# test uses for waitpid(). That is what makes most of the DEGRADED paths
# testable without standing up a real thread pool; they are where the ownership
# bugs live. ngx_alloc() is the REAL one (run.sh links ngx_alloc.o), so the
# task-allocation-failure branch is not injectable and is not covered.
#
# The slice is anchored on exact production lines: from the is_rsa predicate
# through the end of ngx_autocert_keygen_post().

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_order.c"
OUT="$DIR/generated_keygen.inc"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

start=$(grep -nE '^ngx_autocert_keygen_is_rsa\(' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
	echo "✗ could not locate ngx_autocert_keygen_is_rsa in $SRC" >&2
	exit 1
fi
# back up over the `static ngx_int_t` return-type line
start=$((start - 1))
# ...and prove that is what we actually backed up onto. Without this, a
# one-line definition or a dropped line starts the slice inside the block
# comment; every later check still passes (all 7 symbols present, 7 braces)
# and CI dies with a compiler syntax error instead of a layout-drift report.
if ! sed -n "${start}p" "$SRC" | grep -qE '^static '; then
	echo "✗ line $start of $SRC is not the return type of" >&2
	echo "  ngx_autocert_keygen_is_rsa (source layout changed)" >&2
	exit 1
fi

endfn=$(grep -nE '^ngx_autocert_keygen_post\(' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${endfn:-}" ]; then
	echo "✗ could not locate ngx_autocert_keygen_post in $SRC" >&2
	exit 1
fi
if [ "$endfn" -lt "$start" ]; then
	echo "✗ ngx_autocert_keygen_post precedes ngx_autocert_keygen_is_rsa" >&2
	echo "  (source layout changed; the slice is no longer contiguous)" >&2
	exit 1
fi
# first column-0 closing brace at or after _post(): its end
end=$(awk -v s="$endfn" 'NR >= s && $0 == "}" { print NR; exit }' "$SRC")
if [ -z "${end:-}" ]; then
	echo "✗ could not find the end of ngx_autocert_keygen_post" >&2
	exit 1
fi

{
	echo "/* --- RSA keygen offload slot sliced from ngx_autocert_order.c --- */"
	echo "/* Generated by ci/tests/unit/extract_keygen.sh — do not edit by hand. */"
	awk -v s="$start" -v e="$end" 'NR >= s && NR <= e { print }' "$SRC"
} >"$OUT"

for sym in ngx_autocert_keygen_is_rsa ngx_autocert_keygen_t \
	ngx_autocert_keygen_abandon ngx_autocert_keygen_thread \
	ngx_autocert_keygen_completion ngx_autocert_keygen_inline \
	ngx_autocert_keygen_post; do
	if ! grep -q "$sym" "$OUT"; then
		echo "✗ $sym missing from generated output (source layout changed?)" >&2
		rm -f "$OUT"
		exit 1
	fi
done

# The slice must be COMPLETE functions, not a prefix truncated at the first
# nested closing brace -- otherwise the test compiles a fragment and the failure
# surfaces as a confusing syntax error rather than a layout-drift report.
#
# This is a STRUCTURAL check (every sliced function has a column-0 closing
# brace), deliberately NOT a grep for the load-bearing calls themselves.
# Guarding on `ngx_http_autocert_key_free(key);` or the resume call would abort
# extraction whenever someone MUTATES one of those calls -- which is exactly the
# mutation the test's oracle exists to catch. Because this suite aborts at the
# first error, that turned a behavioural mutation into rc=1 with ZERO keygen
# tests run and a layout-drift message, masking the assertion that should have
# gone red. Structural markers drift with the layout; behavioural markers must
# be left to the test.
braces=$(grep -c '^}' "$OUT" || true)
if [ "${braces:-0}" -lt 7 ]; then
	echo "✗ sliced region looks truncated: $braces complete function(s), expected 7" >&2
	echo "  (is_rsa, abandon, thread, completion, inline, post, plus the" >&2
	echo "   slot typedef's close)" >&2
	rm -f "$OUT"
	exit 1
fi

echo "✓ extracted RSA keygen offload slot -> $OUT"
