#!/usr/bin/env bash
#
# Slice the off-event-loop RSA keygen slot out of the shipped
# ../../../src/ngx_autocert_order.c into generated_keygen.inc, compiled by
# ci/tests/unit/test_keygen_offload.c.
#
# Why slice, not include-shim the whole .c: ngx_autocert_order.c is the ACME
# order state machine -- account POST, JSON parser, challenge/ALPN shm zones,
# OpenSSL X509/PEM and a live nginx event loop. The keygen slot itself touches
# only EVP_PKEY, ngx_thread_task_t and ngx_str/ngx_log declarations, so the
# region is lifted verbatim and stays locked to production code with no copy
# drift.
#
# What the slice carries -- the whole cancellation state machine, which is the
# part with a use-after-free hazard in it:
#
#   ngx_autocert_keygen_is_rsa()     which key types are offloaded at all
#   ngx_autocert_keygen_t            the process-lifetime slot
#   ngx_autocert_keygen_abandon()    detach on order_free()
#   ngx_autocert_keygen_thread()     the worker-thread body
#   ngx_autocert_keygen_completion() the event-loop resume/cleanup decision
#
# The test does NOT re-implement any of that: it drives the SHIPPED
# _abandon()/_completion() pair directly, so an ownership bug introduced in
# order.c (freeing into a dead order, leaking the key on the abandoned path,
# releasing the slot too late) fails this suite.
#
# ngx_autocert_keygen_post() is deliberately NOT sliced: it calls
# ngx_thread_pool_get()/ngx_thread_task_post() against a live cycle and thread
# pool, which this TU has no harness for. It is exercised by the module's
# integration path. Everything it decides that is testable without a pool --
# the is_rsa predicate that gates entry to it -- IS sliced.
#
# The slice is anchored on exact production lines: from the is_rsa predicate
# through the end of ngx_autocert_keygen_completion().

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_order.c"
OUT="$DIR/generated_keygen.inc"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

start=$(grep -nE '^ngx_autocert_keygen_is_rsa\(' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
	echo "✗ could not locate ngx_autocert_keygen_is_rsa in $SRC" >&2
	exit 1
fi
# back up over the `static ngx_int_t` return-type line
start=$((start - 1))

endfn=$(grep -nE '^ngx_autocert_keygen_completion\(' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${endfn:-}" ]; then
	echo "✗ could not locate ngx_autocert_keygen_completion in $SRC" >&2
	exit 1
fi
if [ "$endfn" -lt "$start" ]; then
	echo "✗ ngx_autocert_keygen_completion precedes ngx_autocert_keygen_is_rsa" >&2
	echo "  (source layout changed; the slice is no longer contiguous)" >&2
	exit 1
fi
# first column-0 closing brace at or after the completion handler: its end
end=$(awk -v s="$endfn" 'NR >= s && $0 == "}" { print NR; exit }' "$SRC")
if [ -z "${end:-}" ]; then
	echo "✗ could not find the end of ngx_autocert_keygen_completion" >&2
	exit 1
fi

{
	echo "/* --- RSA keygen offload slot sliced from ngx_autocert_order.c --- */"
	echo "/* Generated by ci/tests/unit/extract_keygen.sh — do not edit by hand. */"
	awk -v s="$start" -v e="$end" 'NR >= s && NR <= e { print }' "$SRC"
} >"$OUT"

for sym in ngx_autocert_keygen_is_rsa ngx_autocert_keygen_t \
	ngx_autocert_keygen_abandon ngx_autocert_keygen_thread \
	ngx_autocert_keygen_completion; do
	if ! grep -q "$sym" "$OUT"; then
		echo "✗ $sym missing from generated output (source layout changed?)" >&2
		rm -f "$OUT"
		exit 1
	fi
done

# The slice must be COMPLETE functions, not a prefix truncated at the first
# nested closing brace. Without this the test would compile a fragment and the
# failure would surface as a confusing syntax error rather than a layout-drift
# report. These two lines are the load-bearing ownership decisions in the
# completion handler -- their absence means the slice lost the very behaviour
# the test exists to pin.
if ! grep -q 'ngx_http_autocert_key_free(key);' "$OUT"; then
	echo "✗ sliced completion handler lost the abandoned-order key free" >&2
	rm -f "$OUT"
	exit 1
fi
if ! grep -q 'ngx_autocert_order_finalize_csr(order)' "$OUT"; then
	echo "✗ sliced completion handler lost the resume call" >&2
	rm -f "$OUT"
	exit 1
fi

echo "✓ extracted RSA keygen offload slot -> $OUT"
