#!/usr/bin/env bash
#
# Slice ngx_autocert_acme_log_safe() from the shipped ../../../src/ngx_autocert_acme.c
# into generated_acme_logsafe.inc, compiled by tests/unit/test_acme_logsafe.c
# against <ngx_core.h> + ngx_escape_json.
#
# Why slice: ngx_autocert_acme.c is the ACME client state machine and would pull in
# resolver/SSL/pool/event deps. The log_safe function depends only on
# ngx_str_t/ngx_pool_t/ngx_escape_json, so we lift just it and stay locked to
# production code with no copy drift.
#
# The function runs from its signature line to the first lone "}" in column 1
# (module style). Fail loudly if the target is missing.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_acme.c"
OUT="$DIR/generated_acme_logsafe.inc"
FN="ngx_autocert_acme_log_safe"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

{
	echo "/* --- acme.c ngx_autocert_acme_log_safe and NGX_AUTOCERT_LOG_MAX --- */"
	echo "/* Generated by tests/unit/extract_acme_logsafe.sh — do not edit by hand. */"
} >"$OUT"

# Extract the #define first
grep "^#define NGX_AUTOCERT_LOG_MAX" "$SRC" >>"$OUT" || {
	echo "✗ could not locate NGX_AUTOCERT_LOG_MAX definition in $SRC" >&2
	rm -f "$OUT"
	exit 1
}

echo "" >>"$OUT"

start=$(grep -nE "^ngx_autocert_acme_log_safe\\(" "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
	echo "✗ could not locate definition of ${FN}() in $SRC" >&2
	rm -f "$OUT"
	exit 1
fi
rtype=$((start - 1)) # the return-type line precedes the name

# Extract the function
{
	awk -v s="$rtype" -v name="$FN" '
        NR >= s {
            print
            if (entered && $0 == "}") { exit }
            if ($0 ~ ("^" name "\\(")) { entered = 1 }
        }
    ' "$SRC"

	echo ""
} >>"$OUT"

if ! grep -qE "^ngx_autocert_acme_log_safe\\(" "$OUT"; then
	echo "✗ ${FN} missing from generated output (source layout changed?)" >&2
	rm -f "$OUT"
	exit 1
fi

echo "✓ extracted acme.c helpers -> $OUT"
