#!/usr/bin/env bash
#
# Slice the single pure function ngx_autocert_account_json_safe() out of the
# shipped ../../../src/ngx_autocert_account.c into generated_jsonsafe.inc, compiled by
# tests/unit/test_account_jsonsafe.c against nothing but <ngx_core.h>.
#
# Why slice, not include-shim the whole .c: ngx_autocert_account.c is the ACME
# account state machine and pulls in the acme client, the JSON parser and the
# crypto TU (and their event/SSL/resolver deps) — far too much to link for one
# 12-line byte validator. The function itself depends only on ngx_str_t, so we
# lift just it and stay locked to production code with no copy drift.
#
# The function runs from its signature line ("ngx_autocert_account_json_safe(")
# to the first lone "}" in column 1 (module style). Fail loudly if missing.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_account.c"
OUT="$DIR/generated_jsonsafe.inc"
FN="ngx_autocert_account_json_safe"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

start=$(grep -nE "^${FN}\\(" "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
    echo "✗ could not locate definition of ${FN}() in $SRC" >&2
    exit 1
fi
rtype=$((start - 1))   # the return-type line precedes the name in this style

{
    echo "/* --- ${FN}() sliced from ngx_autocert_account.c --- */"
    echo "/* Generated by tests/unit/extract_jsonsafe.sh — do not edit by hand. */"
    awk -v s="$rtype" -v name="$FN" '
        NR >= s {
            print
            if (entered && $0 == "}") { exit }
            if ($0 ~ ("^" name "\\(")) { entered = 1 }
        }
    ' "$SRC"
} > "$OUT"

if ! grep -qE "^${FN}\\(" "$OUT"; then
    echo "✗ ${FN} missing from generated output (source layout changed?)" >&2
    rm -f "$OUT"
    exit 1
fi

echo "✓ extracted ${FN}() -> $OUT"
