#!/usr/bin/env bash
#
# Slice the win32 store-scan enumeration primitives out of the shipped
# ../../../src/ngx_autocert_win32.h into generated_win32_readdir.inc, compiled
# by ci/tests/unit/test_win32_readdir_err.c ON THE HOST (Linux).
#
# WHY THIS EXISTS. The A6 seed walk distinguishes "clean end of directory" from
# "genuine enumeration failure" via ngx_autocert_readdir_err(). On the POSIX arm
# that channel is errno, which readdir(3) really does leave untouched at EOF. On
# the win32 arm it CANNOT be the ambient global: ngx_autocert_readdir()'s own
# loop skips malformed and unrepresentable entries with `continue` AFTER
# WideCharToMultiByte() has already set LastError, then re-queries, reaches
# STATUS_NO_MORE_FILES and returns NULL for a perfectly clean end-of-directory
# -- with GetLastError() still nonzero. A caller inferring "error" from that
# global reports a spurious failure at the end of every walk that skipped one
# entry, which on a real store means the seed logs an error and stops early.
#
# That is a WIN32-ONLY defect, and .github/workflows/windows-build.yml is
# build-only -- it never runs the unit suite -- so nothing on the Windows side
# would catch a regression here. The Linux unit suite cannot include
# ngx_autocert_win32.h either: it needs windows.h and a win32-configured
# ngx_core.h. Slicing is the way out, and it is the pattern this suite already
# uses for driver.c (extract_seedchunk.sh) and for the win32 rename/link layout
# arithmetic (test_win32_rename_info_layout.c binds to the production macro via
# a POSIX-arm ABI stand-in).
#
# What gets sliced is the PRODUCTION source text of:
#
#   NGX_AUTOCERT_DIRENT / ngx_autocert_dirent_t  the returned entry
#   NGX_AUTOCERT_DIR / ngx_autocert_dir_t   the handle carrying dh->err
#   ngx_autocert_fdopendir()                initialises dh->err = 0
#   ngx_autocert_readdir()                  THE LOOP -- every NULL-returning
#                                           path must set dh->err
#   ngx_autocert_readdir_err()              the accessor under test
#   ngx_autocert_closedir()                 released by the test's handles
#
# The test supplies stand-in Windows types and a scripted
# NtQueryDirectoryFile that returns whatever batch (or NTSTATUS) a case needs.
# So this is not a re-implementation: a regression that drops `dh->err = 0`
# from the STATUS_NO_MORE_FILES path, or forgets to set it on a failure path,
# recompiles into this test and fails it.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_win32.h"
OUT="$DIR/generated_win32_readdir.inc"

if [ ! -f "$SRC" ]; then
	echo "extract_win32_readdir: missing $SRC" >&2
	exit 1
fi

# Slice from the dir-handle struct's typedef through the end of
# ngx_autocert_closedir(). Anchors are production identifiers, not line
# numbers, so ordinary edits above or below the region do not shift the slice.
START='ngx_autocert_dirent_t (W12)'
END='ngx_autocert_closedir(ngx_autocert_dir_t *dh)'

if ! grep -qF "$START" "$SRC"; then
	echo "extract_win32_readdir: start anchor not found in $SRC" >&2
	exit 1
fi
if ! grep -qF "$END" "$SRC"; then
	echo "extract_win32_readdir: end anchor not found in $SRC" >&2
	exit 1
fi

# Emit from the start anchor through the closing brace of closedir(), whose
# signature is the end anchor. `tail` latches on that signature; the first
# line that is exactly "}" after it closes the function and ends the slice.
{
	echo "/* Generated by ci/tests/unit/extract_win32_readdir.sh — do not edit by hand. */"
	echo
	# The start anchor is a line INSIDE the dirent block comment (the most
	# stable unique text in the region -- an identifier line would move with
	# any reformat). Re-open the comment so the slice is valid C.
	echo "/*"
	awk -v s="$START" -v e="$END" '
		index($0, s) { on = 1 }
		!on          { next }
		              { print }
		index($0, e) { tail = 1 }
		tail && $0 == "}" { exit }
	' "$SRC"
} >"$OUT"

# Sanity: the slice must actually contain the paths under test, otherwise a
# silently-empty extraction would make the test vacuously green.
for sym in 'dh->err = 0' 'ngx_autocert_readdir_err' 'STATUS_NO_MORE_FILES' \
	'WideCharToMultiByte' 'ngx_autocert_closedir' 'd_name'; do
	if ! grep -qF "$sym" "$OUT"; then
		echo "extract_win32_readdir: slice is missing '$sym' — anchors drifted" >&2
		exit 1
	fi
done

# A failed query latches dh->eof, so one handle cannot first report a genuine
# error and then be re-driven into STATUS_NO_MORE_FILES. Assert the production
# EOF branch's clearing assignment structurally; the compiled tests separately
# exercise its observable clean verdict after both a skipped and a good entry.
if ! awk '
	/status == STATUS_NO_MORE_FILES/ { eof = 1; next }
	eof && /dh->err = 0/            { found = 1 }
	eof && /return NULL/             { exit !found }
	END                              { if (!found) exit 1 }
' "$OUT"; then
	echo "extract_win32_readdir: STATUS_NO_MORE_FILES does not clear dh->err" >&2
	exit 1
fi

echo "✓ extracted win32 store-scan enumeration primitives -> $OUT"
