#!/usr/bin/env bash
#
# Slice the A6 chunked-seed-walk primitives out of the shipped
# ../../../src/ngx_autocert_driver.c into generated_seedchunk.inc, compiled by
# ci/tests/unit/test_seed_chunk.c.
#
# Why slice, not include-shim the whole .c: ngx_autocert_driver.c is the ACME
# driver — it pulls in the order state machine, the account POST primitive,
# the challenge/ALPN/requests shm zones, OpenSSL and a live nginx event loop.
# The two things this test needs depend only on syscalls and ngx_str:
#
#   NGX_AUTOCERT_SEED_CHUNK          the per-tick entry budget
#   ngx_autocert_seed_read_marker()  the per-entry marker read/skip decision
#
# Slicing them keeps the test bound to production code with no copy drift: if
# the chunk size or the per-entry decision changes in driver.c, this test
# recompiles against the change rather than silently testing a stale copy.
#
# The chunk LOOP itself (ngx_autocert_runtime_seed_step) is not sliced: it
# needs ngx_add_timer, the requests shm zone and ngx_autocert_name_due, i.e. a
# live cycle. The test reconstructs the loop's readdir-cursor discipline
# around the sliced primitives instead, which is exactly the property under
# test — that a walk chunked at NGX_AUTOCERT_SEED_CHUNK and resumed from the
# live DIR* cursor visits the same entry set as the one-shot walk.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_driver.c"
OUT="$DIR/generated_seedchunk.inc"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

chunk=$(grep -nE '^#define NGX_AUTOCERT_SEED_CHUNK' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${chunk:-}" ]; then
	echo "✗ could not locate NGX_AUTOCERT_SEED_CHUNK in $SRC" >&2
	exit 1
fi

start=$(grep -nE '^ngx_autocert_seed_read_marker\(' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
	echo "✗ could not locate ngx_autocert_seed_read_marker in $SRC" >&2
	exit 1
fi
# back up over the `static ngx_int_t` return-type line
start=$((start - 1))

{
	echo "/* --- A6 chunked-seed primitives sliced from ngx_autocert_driver.c --- */"
	echo "/* Generated by ci/tests/unit/extract_seedchunk.sh — do not edit by hand. */"
	sed -n "${chunk}p" "$SRC"
	echo
	awk -v s="$start" '
        NR >= s {
            print
            if ($0 == "}") { exit }
        }
    ' "$SRC"
} >"$OUT"

for sym in NGX_AUTOCERT_SEED_CHUNK ngx_autocert_seed_read_marker; do
	if ! grep -q "$sym" "$OUT"; then
		echo "✗ $sym missing from generated output (source layout changed?)" >&2
		rm -f "$OUT"
		exit 1
	fi
done

# The slice must be a COMPLETE function, not a prefix truncated at the first
# nested closing brace. Without this the test would compile a fragment and the
# failure would surface as a confusing syntax error rather than a layout drift
# report.
if ! grep -q 'return NGX_OK;' "$OUT"; then
	echo "✗ sliced ngx_autocert_seed_read_marker looks truncated (no success return)" >&2
	rm -f "$OUT"
	exit 1
fi

echo "✓ extracted A6 chunked-seed primitives -> $OUT"
