#!/usr/bin/env bash
#
# Slice the A6 chunked-seed-walk primitives out of the shipped
# ../../../src/ngx_autocert_driver.c into generated_seedchunk.inc, compiled by
# ci/tests/unit/test_seed_chunk.c.
#
# Why slice, not include-shim the whole .c: ngx_autocert_driver.c is the ACME
# driver — it pulls in the order state machine, the account POST primitive,
# the challenge/ALPN/requests shm zones, OpenSSL and a live nginx event loop.
# The two things this test needs depend only on syscalls and ngx_str:
#
#   NGX_AUTOCERT_SEED_CHUNK          the per-tick entry budget
#   ngx_autocert_seed_read_marker()  the per-entry marker read/skip decision
#   ngx_autocert_seed_walk_chunk()   THE CHUNK LOOP — the readdir-cursor
#                                    advance, its budget accounting and its
#                                    exhaustion check
#
# Slicing them keeps the test bound to production code with no copy drift: if
# the chunk size, the per-entry decision or the cursor discipline changes in
# driver.c, this test recompiles against the change rather than silently
# testing a stale copy. In particular the test does NOT re-implement the loop:
# a cursor bug introduced in the shipped ngx_autocert_seed_walk_chunk() (an
# exhaustion check moved so the last entry of a chunk is dropped, an off-by-one
# in the budget) is executed by, and fails, the unit suite.
#
# What remains unsliced is only ngx_autocert_runtime_seed_step()'s wrapper:
# the shutdown guard, the per-tick config re-fetch and the ngx_add_timer
# re-arm, which need ngx_add_timer, the requests shm zone and a live cycle.
# The cycle-bound per-entry decisions (name_is_config / name_due /
# requests_ensure / set_state) sit behind the loop's handler hook and are
# supplied by the test, exactly as the driver supplies
# ngx_autocert_seed_restore_entry().

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_driver.c"
OUT="$DIR/generated_seedchunk.inc"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

chunk=$(grep -nE '^#define NGX_AUTOCERT_SEED_CHUNK' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${chunk:-}" ]; then
	echo "✗ could not locate NGX_AUTOCERT_SEED_CHUNK in $SRC" >&2
	exit 1
fi

start=$(grep -nE '^ngx_autocert_seed_read_marker\(' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
	echo "✗ could not locate ngx_autocert_seed_read_marker in $SRC" >&2
	exit 1
fi
# back up over the `static ngx_int_t` return-type line
start=$((start - 1))

# The slice runs from ngx_autocert_seed_read_marker through the end of
# ngx_autocert_seed_walk_chunk. They are adjacent in driver.c on purpose: the
# per-entry decision and the cursor loop that drives it are one testable unit.
loop=$(grep -nE '^ngx_autocert_seed_walk_chunk\(' "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${loop:-}" ]; then
	echo "✗ could not locate ngx_autocert_seed_walk_chunk in $SRC" >&2
	exit 1
fi
if [ "$loop" -lt "$start" ]; then
	echo "✗ ngx_autocert_seed_walk_chunk precedes ngx_autocert_seed_read_marker" >&2
	echo "  (source layout changed; the slice is no longer contiguous)" >&2
	exit 1
fi
# first column-0 closing brace at or after the loop function: its end
end=$(awk -v s="$loop" 'NR >= s && $0 == "}" { print NR; exit }' "$SRC")
if [ -z "${end:-}" ]; then
	echo "✗ could not find the end of ngx_autocert_seed_walk_chunk" >&2
	exit 1
fi

# The handler typedef sits between read_marker and walk_chunk, so the
# contiguous slice already carries it. Locate it anyway: its absence means the
# layout moved and the slice would no longer compile.
tstart=$(grep -nE '^typedef ngx_int_t \(\*ngx_autocert_seed_entry_pt\)' "$SRC" \
	| head -1 | cut -d: -f1 || true)
if [ -z "${tstart:-}" ]; then
	echo "✗ could not locate ngx_autocert_seed_entry_pt in $SRC" >&2
	exit 1
fi

{
	echo "/* --- A6 chunked-seed primitives sliced from ngx_autocert_driver.c --- */"
	echo "/* Generated by ci/tests/unit/extract_seedchunk.sh — do not edit by hand. */"
	sed -n "${chunk}p" "$SRC"
	echo
	awk -v s="$start" -v e="$end" '
        NR >= s && NR <= e { print }
    ' "$SRC"
} >"$OUT"

for sym in NGX_AUTOCERT_SEED_CHUNK ngx_autocert_seed_read_marker \
	ngx_autocert_seed_entry_pt ngx_autocert_seed_walk_chunk; do
	if ! grep -q "$sym" "$OUT"; then
		echo "✗ $sym missing from generated output (source layout changed?)" >&2
		rm -f "$OUT"
		exit 1
	fi
done

# The slice must be a COMPLETE function, not a prefix truncated at the first
# nested closing brace. Without this the test would compile a fragment and the
# failure would surface as a confusing syntax error rather than a layout drift
# report.
if ! grep -q 'return NGX_OK;' "$OUT"; then
	echo "✗ sliced ngx_autocert_seed_read_marker looks truncated (no success return)" >&2
	rm -f "$OUT"
	exit 1
fi
if ! grep -q 'return NGX_AGAIN;' "$OUT"; then
	echo "✗ sliced ngx_autocert_seed_walk_chunk looks truncated (no budget-spent return)" >&2
	rm -f "$OUT"
	exit 1
fi

echo "✓ extracted A6 chunked-seed primitives (incl. the chunk loop) -> $OUT"
