#!/usr/bin/env bash
#
# Slice pure functions out of the shipped ../../../src/ngx_autocert_account.c
# into generated_jsonsafe.inc, compiled by tests/unit/test_account_jsonsafe.c
# against nothing but <ngx_core.h> (+ ngx_string.o for ngx_escape_json, linked
# by run.sh for the log_safe half only).
#
# Why slice, not include-shim the whole .c: ngx_autocert_account.c is the ACME
# account state machine and pulls in the acme client, the JSON parser and the
# crypto TU (and their event/SSL/resolver deps) — far too much to link for a
# couple of small byte helpers. Both functions here depend on nothing but
# ngx_str_t/ngx_escape_json, so we lift just them and stay locked to
# production code with no copy drift.
#
# Each function body runs from its signature line through the line where
# brace depth returns to zero -- see lib/slice.sh for the extraction rule,
# its rationale and its documented literal/comment limitation.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=ci/tests/unit/lib/slice.sh
source "$DIR/lib/slice.sh"
SRC="$DIR/../../../src/ngx_autocert_account.c"
OUT="$DIR/generated_jsonsafe.inc"
FNS=(
    "ngx_autocert_account_json_safe"
    "ngx_autocert_account_log_safe"
)

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

{
    echo "/* --- account.c pure-function slices --- */"
    echo "/* Generated by tests/unit/extract_jsonsafe.sh — do not edit by hand. */"
} > "$OUT"

for FN in "${FNS[@]}"; do
    if ! rtype=$(slice_find_start "$SRC" "$FN"); then
        echo "✗ could not locate definition of ${FN}() in $SRC" >&2
        rm -f "$OUT"
        exit 1
    fi

    # Wrap each slice in its own opt-out guard. A consumer may need only ONE
    # of these helpers -- test_name_valid.c uses json_safe alone. log_safe is
    # `static` in production, so a TU that includes the slice without calling
    # it trips -Werror=unused-function AND drags in ngx_escape_json at link
    # time; either one fails the build, which means that test silently stops
    # running. Such a consumer defines NGX_AUTOCERT_SLICE_SKIP_<FN> before the
    # include. Guarding beats __attribute__((unused)): that silences the
    # warning but still emits the body, so the link dependency remains.
    rc=0
    body=$(slice_function "$SRC" "$rtype" "$FN") || rc=$?
    if [ "$rc" -ne 0 ]; then
        if [ "$rc" -eq 2 ]; then
            echo "✗ ${FN}(): brace depth went negative in $SRC (unmatched '}' in a string/char literal or comment?)" >&2
        else
            echo "✗ ${FN}() body never closed at brace depth 0 in $SRC (reformatted?)" >&2
        fi
        rm -f "$OUT"
        exit 1
    fi

    {
        printf '#ifndef NGX_AUTOCERT_SLICE_SKIP_%s\n' "$FN"
        printf '%s\n' "$body"
        printf '#endif /* NGX_AUTOCERT_SLICE_SKIP_%s */\n' "$FN"
        echo ""
    } >> "$OUT"
done

for FN in "${FNS[@]}"; do
    if ! grep -qE "^${FN}\\(" "$OUT"; then
        echo "✗ ${FN} missing from generated output (source layout changed?)" >&2
        rm -f "$OUT"
        exit 1
    fi
done

echo "✓ extracted account.c helpers -> $OUT"
