#!/usr/bin/env bash
#
# Slice ngx_autocert_acme_log_safe() from the shipped ../../../src/ngx_autocert_acme.c
# into generated_acme_logsafe.inc, compiled by tests/unit/test_acme_logsafe.c
# against <ngx_core.h> + ngx_escape_json.
#
# Why slice: ngx_autocert_acme.c is the ACME client state machine and would pull in
# resolver/SSL/pool/event deps. The log_safe function depends only on
# ngx_str_t/ngx_pool_t/ngx_escape_json, so we lift just it and stay locked to
# production code with no copy drift.
#
# The function body runs from its signature line through the line where
# brace depth returns to zero -- see lib/slice.sh for the extraction rule,
# its rationale and its documented literal/comment limitation. Fail loudly if
# the target is missing.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=ci/tests/unit/lib/slice.sh
source "$DIR/lib/slice.sh"
SRC="$DIR/../../../src/ngx_autocert_acme.c"
OUT="$DIR/generated_acme_logsafe.inc"
FN="ngx_autocert_acme_log_safe"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

{
	echo "/* --- acme.c ngx_autocert_acme_log_safe and NGX_AUTOCERT_LOG_MAX --- */"
	echo "/* Generated by tests/unit/extract_acme_logsafe.sh — do not edit by hand. */"
} >"$OUT"

# Extract the #define first
grep "^#define NGX_AUTOCERT_LOG_MAX" "$SRC" >>"$OUT" || {
	echo "✗ could not locate NGX_AUTOCERT_LOG_MAX definition in $SRC" >&2
	rm -f "$OUT"
	exit 1
}

echo "" >>"$OUT"

if ! rtype=$(slice_find_start "$SRC" "$FN"); then
	echo "✗ could not locate definition of ${FN}() in $SRC" >&2
	rm -f "$OUT"
	exit 1
fi

# Extract the function. Captured into a variable rather than redirected into
# $OUT inside a block: shellcheck's SC2094 fires (info, and CI gates on info)
# whenever a block that writes $OUT also mentions it, even in an error branch.
rc=0
body=$(slice_function "$SRC" "$rtype" "$FN") || rc=$?
if [ "$rc" -ne 0 ]; then
	if [ "$rc" -eq 2 ]; then
		echo "✗ ${FN}(): brace depth went negative in $SRC (unmatched '}' in a string/char literal or comment?)" >&2
	elif [ "$rc" -eq 4 ]; then
		echo "✗ ${FN}(): $SRC is missing or unreadable" >&2
	else
		echo "✗ ${FN}() body never closed at brace depth 0 in $SRC (reformatted?)" >&2
	fi
	rm -f "$OUT"
	exit 1
fi

printf '%s\n\n' "$body" >>"$OUT"

if ! grep -qE "^ngx_autocert_acme_log_safe\\(" "$OUT"; then
	echo "✗ ${FN} missing from generated output (source layout changed?)" >&2
	rm -f "$OUT"
	exit 1
fi

echo "✓ extracted acme.c helpers -> $OUT"
