#!/usr/bin/env bash
#
# Slice the slot struct + sentinel + ngx_autocert_slot_fresh() out of the
# shipped ../../../src/ngx_autocert_serve.c into generated_slotfresh.inc,
# compiled by tests/unit/test_slot_fresh.c against nothing but <ngx_core.h> +
# OpenSSL's opaque X509/EVP_PKEY type declarations (never linked, only the
# struct layout is needed).
#
# Why slice, not include-shim the whole .c: ngx_autocert_serve.c is the SSL
# cert_cb + PEM-parse + ACME order reload path and pulls in
# ngx_http_ssl_module.h / ngx_http_v2_module.h / ngx_http_v3.h plus a live
# OpenSSL link -- far too much to stand up for one freshness-key predicate.
# The predicate itself depends only on the slot struct's three key fields, so
# we lift the struct, its "never loaded" sentinel, and the function, and stay
# locked to production code with no copy drift.
#
# Three independent slices, each anchored on an exact production line so a
# source-layout change fails loudly instead of silently including drift:
#   1. "typedef struct {" ... "} ngx_autocert_slot_t;"   (the slot fields)
#   2. the NGX_AUTOCERT_UNIQ_NEVER_LOADED #define line
#   3. the ngx_autocert_slot_fresh() function body

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_autocert_serve.c"
OUT="$DIR/generated_slotfresh.inc"
FN="ngx_autocert_slot_fresh"

if [ ! -f "$SRC" ]; then
	echo "✗ cannot find $SRC" >&2
	exit 1
fi

struct_slice=$(awk '
    /^typedef struct \{$/ && !found_start { start = NR; found_start = 1 }
    found_start { buf = buf $0 "\n" }
    found_start && /^\} ngx_autocert_slot_t;$/ { print buf; exit }
' "$SRC")

sentinel_line=$(grep -E '^#define NGX_AUTOCERT_UNIQ_NEVER_LOADED' "$SRC" || true)

fn_start=$(grep -nE "^${FN}\\(" "$SRC" | head -1 | cut -d: -f1 || true)

if [ -z "$struct_slice" ]; then
	echo "✗ could not locate ngx_autocert_slot_t in $SRC" >&2
	exit 1
fi
if [ -z "$sentinel_line" ]; then
	echo "✗ could not locate NGX_AUTOCERT_UNIQ_NEVER_LOADED in $SRC" >&2
	exit 1
fi
if [ -z "${fn_start:-}" ]; then
	echo "✗ could not locate ${FN}() in $SRC" >&2
	exit 1
fi
rtype=$((fn_start - 1)) # the return-type line precedes the name in this style

{
	echo "/* --- slot struct + sentinel + ${FN}() sliced from"
	echo " * ngx_autocert_serve.c --- */"
	echo "/* Generated by tests/unit/extract_slotfresh.sh — do not edit by hand. */"
	printf '%s\n' "$struct_slice"
	printf '%s\n' "$sentinel_line"
	awk -v s="$rtype" -v name="$FN" '
        NR >= s {
            print
            if (entered && $0 == "}") { exit }
            if ($0 ~ ("^" name "\\(")) { entered = 1 }
        }
    ' "$SRC"
} >"$OUT"

if ! grep -qE "^${FN}\\(" "$OUT"; then
	echo "✗ ${FN} missing from generated output (source layout changed?)" >&2
	rm -f "$OUT"
	exit 1
fi
if ! grep -q "ngx_autocert_slot_t;" "$OUT"; then
	echo "✗ slot struct missing from generated output (source layout changed?)" >&2
	rm -f "$OUT"
	exit 1
fi

echo "✓ extracted slot struct + sentinel + ${FN}() -> $OUT"
