#!/usr/bin/env bash
#
# Slice the pure HTTP-response/URL parser functions out of the shipped
# ../../src/ngx_autocert_acme.c into generated_http.inc for standalone
# compilation against ngx_http_shim.h — no real nginx headers, no event/SSL/
# resolver tree required.
#
# Why slice (not include the whole .c): ngx_autocert_acme.c is an event-driven
# TLS client; including it would drag in ngx_event_connect / ngx_resolver /
# ngx_ssl and their transitive symbols at link time, even though only the
# parser functions are exercised. We extract exactly the self-contained byte
# crunchers, which depend on nothing but ngx_string/ngx_array helpers the shim
# provides. This keeps the harness locked to production code with no copy drift.
#
# Extracted (in source order, by exact function signature):
#   ngx_autocert_acme_url_part_safe   static URL-component byte validator
#   ngx_autocert_acme_parse_url       static absolute-https URL splitter
#   ngx_autocert_memmem               static NUL-free needle search
#   ngx_autocert_acme_header          public header lookup
#   ngx_autocert_acme_parse_response  static incremental response parser
#   ngx_autocert_acme_chunk_size      static guarded hex chunk-size parser
#   ngx_autocert_acme_dechunk         static chunked-body decoder
#
# A function body runs from its signature line to the first line that is a lone
# "}" in column 1 (the module's style). We fail loudly if any target is missing.

set -euo pipefail

FUZZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$FUZZ_DIR/../../src/ngx_autocert_acme.c"
OUT="$FUZZ_DIR/generated_http.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

# The functions to lift, by the token that begins their definition line. The
# return-type line precedes the name line in this codebase's style, so we key
# on the name-and-open-paren and walk backwards to the return type.
fns=(
    "ngx_autocert_acme_url_part_safe"
    "ngx_autocert_acme_parse_url"
    "ngx_autocert_memmem"
    "ngx_autocert_acme_header"
    "ngx_autocert_acme_parse_response"
    "ngx_autocert_acme_chunk_size"
    "ngx_autocert_acme_dechunk"
)

{
    echo "/* --- HTTP parser bodies sliced from ngx_autocert_acme.c --- */"
    echo "/* Generated by fuzz/extract_http.sh — do not edit by hand. */"
    echo ""
} > "$OUT"

for fn in "${fns[@]}"; do
    # Find the definition line: a line that is exactly "<fn>(" at column 0
    # (the name sits on its own line after the return type in this style).
    start=$(grep -nE "^${fn}\\(" "$SRC" | head -1 | cut -d: -f1 || true)
    if [ -z "${start:-}" ]; then
        echo "✗ could not locate definition of ${fn}() in $SRC" >&2
        rm -f "$OUT"
        exit 1
    fi
    # Back up over the return-type line(s): include the single preceding line
    # (the return type). Walk back while the previous line is non-blank and not
    # itself a closing brace / blank separator.
    rtype=$((start - 1))
    awk -v s="$rtype" -v name="$fn" '
        NR == s { rt = $0 }
        NR >= s {
            print
            # Stop at the first lone "}" at column 1 AFTER we entered the body.
            if (entered && $0 == "}") { exit }
            if ($0 ~ ("^" name "\\(")) { entered = 1 }
        }
    ' "$SRC" >> "$OUT"
    echo "" >> "$OUT"
done

# Sanity: every target must be present in the output.
for fn in "${fns[@]}"; do
    if ! grep -qE "^${fn}\\(" "$OUT"; then
        echo "✗ ${fn} missing from generated output (source layout changed?)" >&2
        rm -f "$OUT"
        exit 1
    fi
done

LINES=$(wc -l < "$OUT")
echo "✓ extracted HTTP parser bodies — $LINES lines -> $OUT"
