#!/usr/bin/env bash
#
# Slice the pure HTTP-response/URL parser functions out of the shipped
# ../../src/ngx_autocert_acme.c into generated_http.inc for standalone
# compilation against ngx_http_shim.h — no real nginx headers, no event/SSL/
# resolver tree required.
#
# Why slice (not include the whole .c): ngx_autocert_acme.c is an event-driven
# TLS client; including it would drag in ngx_event_connect / ngx_resolver /
# ngx_ssl and their transitive symbols at link time, even though only the
# parser functions are exercised. We extract exactly the self-contained byte
# crunchers, which depend on nothing but ngx_string/ngx_array helpers the shim
# provides. This keeps the harness locked to production code with no copy drift.
#
# Extracted (in source order, by exact function signature):
#   ngx_autocert_acme_url_part_safe   static URL-component byte validator
#   ngx_autocert_acme_parse_url       static absolute-https URL splitter
#   ngx_autocert_memmem               static NUL-free needle search
#   ngx_autocert_acme_header          public header lookup
#   ngx_autocert_acme_parse_response  static incremental response parser
#   ngx_autocert_acme_chunk_size      static guarded hex chunk-size parser
#   ngx_autocert_acme_dechunk         static chunked-body decoder
#
# Each function body runs from its signature line through the line where
# brace depth returns to zero -- see ../tests/unit/lib/slice.sh for the
# extraction rule, its rationale and its documented literal/comment
# limitation. We fail loudly if any target is missing.

set -euo pipefail

FUZZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=ci/tests/unit/lib/slice.sh
source "$FUZZ_DIR/../tests/unit/lib/slice.sh"
SRC="$FUZZ_DIR/../../src/ngx_autocert_acme.c"
OUT="$FUZZ_DIR/generated_http.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

# The functions to lift, by the token that begins their definition line. The
# return-type line precedes the name line in this codebase's style, so we key
# on the name-and-open-paren and walk backwards to the return type.
fns=(
    "ngx_autocert_acme_url_part_safe"
    "ngx_autocert_acme_parse_url"
    "ngx_autocert_memmem"
    "ngx_autocert_acme_header"
    "ngx_autocert_acme_parse_response"
    "ngx_autocert_acme_chunk_size"
    "ngx_autocert_acme_dechunk"
)

{
    echo "/* --- HTTP parser bodies sliced from ngx_autocert_acme.c --- */"
    echo "/* Generated by fuzz/extract_http.sh — do not edit by hand. */"
    echo ""
    grep '^#define NGX_AUTOCERT_DECHUNK_' "$SRC" || true
    echo ""
} > "$OUT"

if [ "$(grep -c '^#define NGX_AUTOCERT_DECHUNK_' "$OUT")" -ne 3 ]; then
    echo "✗ expected exactly three dechunk state constants in $SRC" >&2
    rm -f "$OUT"
    exit 1
fi

for fn in "${fns[@]}"; do
    if ! rtype=$(slice_find_start "$SRC" "$fn"); then
        echo "✗ could not locate definition of ${fn}() in $SRC" >&2
        rm -f "$OUT"
        exit 1
    fi

    rc=0
    body=$(slice_function "$SRC" "$rtype" "$fn") || rc=$?
    if [ "$rc" -ne 0 ]; then
        if [ "$rc" -eq 2 ]; then
            echo "✗ ${fn}(): brace depth went negative in $SRC (unmatched '}' in a string/char literal or comment?)" >&2
        elif [ "$rc" -eq 4 ]; then
            echo "✗ ${fn}(): $SRC is missing or unreadable" >&2
        else
            echo "✗ ${fn}() body never closed at brace depth 0 in $SRC (reformatted?)" >&2
        fi
        rm -f "$OUT"
        exit 1
    fi

    printf '%s\n\n' "$body" >> "$OUT"
done

# Sanity: every target must be present in the output.
for fn in "${fns[@]}"; do
    if ! grep -qE "^${fn}\\(" "$OUT"; then
        echo "✗ ${fn} missing from generated output (source layout changed?)" >&2
        rm -f "$OUT"
        exit 1
    fi
done

LINES=$(wc -l < "$OUT")
echo "✓ extracted HTTP parser bodies — $LINES lines -> $OUT"
