#!/usr/bin/env bash
#
# Slice ngx_http_autocert_base64url_decode() out of the shipped
# ../../src/ngx_http_autocert_crypto.c into generated_b64.inc for standalone
# compilation against ngx_b64_shim.h — no real nginx headers, no OpenSSL.
#
# Why slice just this one function: ngx_http_autocert_crypto.c pulls in
# OpenSSL EC/BN/X509 headers and JOSE-signing state for the rest of the file;
# the base64url decode wrapper only touches ngx_pnalloc / ngx_str_t /
# ngx_decode_base64url, so slicing avoids linking OpenSSL just to fuzz the
# byte cruncher. This keeps the fuzz target locked to production code: there
# is no hand-copied parser.
#
# Extracted (by exact function signature, source order):
#   ngx_http_autocert_base64url_decode   strict RFC4648§5 alphabet check +
#                                         size-arithmetic guard + decode
#
# A function body runs from its signature line to the first line that is a
# lone "}" in column 1 (the module's style). Fails loudly if not found.

set -euo pipefail

FUZZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$FUZZ_DIR/../../src/ngx_http_autocert_crypto.c"
OUT="$FUZZ_DIR/generated_b64.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

fn="ngx_http_autocert_base64url_decode"

start=$(grep -nE "^${fn}\\(" "$SRC" | head -1 | cut -d: -f1 || true)
if [ -z "${start:-}" ]; then
    echo "✗ could not locate definition of ${fn}() in $SRC" >&2
    exit 1
fi
rtype=$((start - 1))

{
    echo "/* --- base64url decode body sliced from ngx_http_autocert_crypto.c --- */"
    echo "/* Generated by fuzz/extract_b64.sh — do not edit by hand. */"
    echo ""
} > "$OUT"

awk -v s="$rtype" -v name="$fn" '
    NR == s { rt = $0 }
    NR >= s {
        print
        if (entered && $0 == "}") { exit }
        if ($0 ~ ("^" name "\\(")) { entered = 1 }
    }
' "$SRC" >> "$OUT"

if ! grep -qE "^${fn}\\(" "$OUT"; then
    echo "✗ ${fn} missing from generated output (source layout changed?)" >&2
    rm -f "$OUT"
    exit 1
fi

LINES=$(wc -l < "$OUT")
echo "✓ extracted base64url decode body — $LINES lines -> $OUT"
