/*
 * libFuzzer harness for ngx_http_autocert_base64url_decode().
 *
 * Why this target: the decode wrapper is a hand-written strict RFC 4648 §5
 * URL-safe-alphabet validator layered on top of nginx's own (permissive)
 * ngx_decode_base64url() — the module rejects any byte outside A-Za-z0-9-_
 * (in particular '=' padding) rather than let nginx's decoder silently stop
 * at the first bad byte, because a hostile/MITM'd ACME response encoding a
 * JWS field this way must be rejected outright, not silently truncated. The
 * validation loop plus the ((n+3)/4)*3 size-arithmetic overflow guard is
 * module-owned parsing logic that fuzz_json/fuzz_http do not exercise.
 * Currently the only in-tree caller passes an operator-configured EAB HMAC
 * key (not ACME-response bytes), but the function is the module's
 * general-purpose base64url decoder and the highest-value target for any
 * future ACME-response-derived base64url field (this codebase already JWS-
 * signs every POST, so a base64url-encoded value arriving in a future
 * ACME response — e.g. an extension field — would hit this exact code path).
 *
 * The real function body lives in ../../src/ngx_http_autocert_crypto.c and
 * depends on OpenSSL/the nginx tree for the rest of that file; extract_b64.sh
 * slices just this one self-contained function into generated_b64.inc at
 * build time, compiled against the minimal ngx_b64_shim.h (which also
 * carries a verbatim copy of nginx core's ngx_decode_base64url() — a fixed
 * nginx-version dependency, not module code, so it is not itself sliced).
 * We always fuzz the SHIPPED wrapper with no copy drift.
 *
 * The harness allocates the input buffer sized EXACTLY to `size` bytes with
 * no trailing NUL, so ASAN turns any read at or past the end into an
 * immediate heap-buffer-overflow.
 *
 * Build (see fuzz/build.sh):
 *   CC=clang bash fuzz/build.sh     -> fuzz/fuzz_b64 (ASan+UBSan+fuzzer)
 *
 * Run:
 *   cd fuzz && ./fuzz_b64 -max_total_time=120 -print_final_stats=1 corpus_b64/
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Shim first: provides ngx_str_t, ngx_pool_t, ngx_decode_base64url, etc. */
#include "ngx_b64_shim.h"

/* Generated by fuzz/extract_b64.sh from ../../src/ngx_http_autocert_crypto.c. */
#include "generated_b64.inc"

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    ngx_pool_t   pool;
    ngx_log_t    log;
    ngx_str_t    in, out;
    u_char      *buf;
    size_t       alloc;

    log.dummy = 0;
    pool.nallocs = 0;
    pool.log = &log;

    /*
     * Allocate EXACTLY `size` bytes (one byte when size == 0, since
     * malloc(0) is implementation-defined) and do NOT NUL-terminate: any
     * read at or past buf+size becomes an ASAN heap-buffer-overflow.
     */
    alloc = size ? size : 1;
    buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }
    if (size) {
        memcpy(buf, data, size);
    }

    in.data = buf;
    in.len = size;
    out.data = NULL;
    out.len = 0;

    (void) ngx_http_autocert_base64url_decode(&pool, &in, &out);

    ngx_fuzz_pool_reset(&pool);
    free(buf);
    return 0;
}
