/*
 * libFuzzer harness for ngx_autocert_json_parse() and the JSON accessors.
 *
 * Why this target: ngx_autocert_json_parse() reads ACME server response
 * bodies — bytes that arrive over a verified-TLS channel but are still
 * attacker-influenceable (compromised CA, hostile redirect, buggy server).
 * The parser is written defensively (bounded depth, length-delimited,
 * no NUL reliance) but a single off-by-one in the string escape decoder,
 * the surrogate-pair branch, or the number/literal scanner would be a
 * worker-crashing OOB read. Coverage-guided fuzzing catches that class of
 * bug and the ACME integration tests miss.
 *
 * The real parser bodies live in ../../src/ngx_autocert_json.c and depend
 * on the nginx tree; fuzz/extract_parser.sh slices the entire .c (and the
 * type declarations from the .h) into generated_json.inc at build time,
 * compiled against the minimal ngx_shim.h rather than real nginx headers.
 * We always fuzz the SHIPPED code with no copy drift.
 *
 * The harness allocates a buffer sized EXACTLY to `size` bytes with no
 * trailing NUL, so ASAN turns any read at or past the end into an immediate
 * heap-buffer-overflow. It also exercises the main accessor functions on
 * every non-NULL parse result so their pointer arithmetic is covered too.
 *
 * Build (see fuzz/build.sh):
 *   CC=clang bash fuzz/build.sh     -> fuzz/fuzz_json (ASan+UBSan+fuzzer)
 *   CC=clang CFLAGS='-g -O1' bash fuzz/build.sh  -> plain CFLAGS path
 *
 * Run:
 *   cd fuzz && ./fuzz_json -max_total_time=120 -print_final_stats=1 corpus/
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Shim first: provides all nginx types, pool, log, and macros. */
#include "ngx_shim.h"

/* Generated by fuzz/extract_parser.sh from ../../src/ngx_autocert_json.c.
 * Contains the type declarations (stripped from .h) and all parser function
 * bodies in source order, compiled against ngx_shim.h only. */
#include "generated_json.inc"

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    ngx_pool_t                   pool;
    ngx_log_t                    log;
    u_char                      *buf;
    size_t                       alloc;
    ngx_autocert_json_value_t   *root, *child;
    ngx_str_t                    s;
    ngx_int_t                    n;

    /* Wire up the pool: log field must be non-NULL because the parser
     * dereferences pool->log in ngx_log_debug1 call sites (even though
     * our shim macro expands them to (void)0, the field read happens at
     * the call site before macro expansion in some compiler evaluations;
     * giving it a valid address is the safe choice).
     *
     * `size` is also the allocation budget's denominator: the shim aborts if
     * the parser's total allocation count or byte total exceeds the linear
     * bound derived from it (see ngx_shim.h). That abort is the oracle for
     * allocation blowup, which neither ASan nor a NULL-returning cap can
     * detect. */
    log.dummy = 0;
    ngx_fuzz_pool_init(&pool, &log, size);

    /*
     * Allocate EXACTLY `size` bytes (one byte when size == 0, since
     * malloc(0) is implementation-defined) and do NOT NUL-terminate: any
     * read at or past buf+size becomes an ASAN heap-buffer-overflow.
     */
    alloc = size ? size : 1;
    buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }
    if (size) {
        memcpy(buf, data, size);
    }

    root = ngx_autocert_json_parse(&pool, buf, size);

    if (root != NULL) {
        /* Exercise the object accessor on any root value — it is a no-op
         * (returns NULL) if root is not an OBJECT, which is fine. */
        child = ngx_autocert_json_object_get(root, "status");
        (void) child;

        (void) ngx_autocert_json_object_str(root, "newNonce", &s);
        (void) ngx_autocert_json_object_str(root, "newAccount", &s);
        (void) ngx_autocert_json_object_str(root, "newOrder", &s);
        (void) ngx_autocert_json_object_str(root, "finalize", &s);
        (void) ngx_autocert_json_object_str(root, "expires", &s);
        (void) ngx_autocert_json_object_str(root, "status", &s);

        /* Exercise array accessors. */
        (void) ngx_autocert_json_array_count(root);
        child = ngx_autocert_json_array_item(root, 0);
        (void) child;
        child = ngx_autocert_json_array_item(root, 1);
        (void) child;

        /* Exercise number parsing if the root or first array element is a
         * number — exercises the integer overflow guard. */
        if (root->type == NGX_AUTOCERT_JSON_NUMBER) {
            (void) ngx_autocert_json_number_int(root, &n);
        }
        child = ngx_autocert_json_array_item(root, 0);
        if (child != NULL && child->type == NGX_AUTOCERT_JSON_NUMBER) {
            (void) ngx_autocert_json_number_int(child, &n);
        }

        /* If root is an object, walk into "meta" / "identifiers" to exercise
         * nested object + array traversal (same code paths as the ACME client
         * uses when processing a directory or order response). */
        if (root->type == NGX_AUTOCERT_JSON_OBJECT) {
            ngx_autocert_json_value_t *meta =
                ngx_autocert_json_object_get(root, "meta");
            if (meta != NULL) {
                (void) ngx_autocert_json_object_str(meta, "termsOfService", &s);
            }

            ngx_autocert_json_value_t *ids =
                ngx_autocert_json_object_get(root, "identifiers");
            if (ids != NULL) {
                ngx_uint_t cnt = ngx_autocert_json_array_count(ids);
                ngx_uint_t i;
                for (i = 0; i < cnt && i < 8; i++) {
                    ngx_autocert_json_value_t *id =
                        ngx_autocert_json_array_item(ids, i);
                    if (id != NULL) {
                        (void) ngx_autocert_json_object_str(id, "type", &s);
                        (void) ngx_autocert_json_object_str(id, "value", &s);
                    }
                }
            }
        }
    }

    ngx_fuzz_pool_reset(&pool);
    free(buf);
    return 0;
}
