/*
 * ngx_autocert_alpn — shared-memory tls-alpn-01 challenge certificate store
 * (M10b).
 *
 * For the RFC 8737 tls-alpn-01 challenge the CA validates domain control by
 * opening a TLS connection with ALPN "acme-tls/1" + SNI=<domain> and checking
 * that the served certificate carries the id-pe-acmeIdentifier extension built
 * from SHA-256(keyauth). That validation handshake lands on a WORKER process,
 * but the challenge certificate is generated by the ACME helper process — so
 * the per-domain {cert,key} pair must cross the process boundary, exactly like
 * the HTTP-01 token store (ngx_autocert_challenge).
 *
 * This is that map: an rbtree in a shared-memory slab zone, keyed by
 * crc32(domain) with the full domain compared on collision, written by the
 * helper and read by the workers under the zone's slab mutex. The value is a
 * PEM-encoded leaf certificate plus its PEM-encoded private key (the challenge
 * cert is self-signed, so there is no chain).
 *
 * The store functions are compiled into BOTH the CORE helper module (writer)
 * and the HTTP module (reader): the two .so do not cross-resolve symbols and
 * both address the same shared slab through the zone, so a duplicated copy in
 * each is correct (cf. ngx_autocert_challenge / the crypto TU). The shared
 * header fixes the node layout both copies must agree on.
 *
 * Domain key contract: the domain is matched byte-exact (crc32 + memcmp), so
 * the writer and reader MUST agree on casing. This store does NOT lowercase
 * internally — callers must pass an already NORMALIZED (lowercased) DNS name.
 * The production paths honour this: server_name is lowercased by nginx at
 * config time (so the helper inserts a lowercased name) and the worker
 * lowercases the SNI before ngx_autocert_alpn_get(). The one exception is the
 * test-only `autocert_test_alpn` directive, which seeds its argument verbatim;
 * a mixed-case test domain therefore won't be found and must be given in lower
 * case.
 */

#ifndef _NGX_AUTOCERT_ALPN_H_INCLUDED_
#define _NGX_AUTOCERT_ALPN_H_INCLUDED_


#include <ngx_config.h>
#include <ngx_core.h>


/*
 * Challenge-type selector shared with the CORE order/helper TUs (which don't
 * include the HTTP module's conf header). Values MUST match
 * ngx_http_autocert_challenge_e in ngx_http_autocert_conf.h.
 */
#define NGX_AUTOCERT_CHALLENGE_HTTP_01       0
#define NGX_AUTOCERT_CHALLENGE_TLS_ALPN_01   1
#define NGX_AUTOCERT_CHALLENGE_DNS_01        2


/* Upper bounds (defensive). A DNS name is <= 255; a P-256/P-384 self-signed
 * challenge cert PEM and its PKCS#8 key PEM are well under a few KB. */
#define NGX_AUTOCERT_ALPN_DOMAIN_MAX   255
#define NGX_AUTOCERT_ALPN_CERT_MAX     8192
#define NGX_AUTOCERT_ALPN_KEY_MAX      8192


/* One entry in the slab rbtree: domain is the key, {cert,key} PEM the value.
 * The domain bytes follow the node inline (str rbtree node convention); cert
 * and key are separate slab allocations pointed to by their ngx_str_t. */
typedef struct {
    ngx_rbtree_node_t   node;        /* node.key = ngx_crc32 of the domain */
    ngx_str_t           cert;        /* slab-allocated leaf cert PEM */
    ngx_str_t           key;         /* slab-allocated private key PEM */
    u_short             domain_len;
    u_char              domain[1];   /* domain_len bytes, inline */
} ngx_autocert_alpn_node_t;


/* Zone-wide shared header (lives at shpool->data). */
typedef struct {
    ngx_rbtree_t        rbtree;
    ngx_rbtree_node_t   sentinel;
} ngx_autocert_alpn_sh_t;


/*
 * Zone init callback for ngx_shared_memory_add(): sets up the rbtree in the
 * slab. Pass as shm_zone->init; data is ignored. Inherits the previous
 * incarnation's tree across reload (noreuse off).
 */
ngx_int_t ngx_autocert_alpn_init_zone(ngx_shm_zone_t *shm_zone, void *data);


/*
 * Insert or replace domain->{cert,key} in the zone (helper side). Copies all
 * three into slab memory under the slab mutex. Returns NGX_OK, NGX_ERROR on a
 * bad argument / slab OOM. Re-inserting an existing domain replaces its value.
 */
ngx_int_t ngx_autocert_alpn_set(ngx_shm_zone_t *shm_zone, ngx_str_t *domain,
    ngx_str_t *cert, ngx_str_t *key);


/*
 * Remove a domain (helper side, after the authorization is validated). Returns
 * NGX_OK whether or not it was present.
 */
ngx_int_t ngx_autocert_alpn_remove(ngx_shm_zone_t *shm_zone, ngx_str_t *domain);

/*
 * Look up a domain and copy its cert+key PEM into the *cert and *key outputs,
 * allocated from `pool` (worker side, in the handshake). Returns NGX_OK if
 * found, NGX_DECLINED
 * if absent, NGX_ERROR on a bad argument / OOM. Copying out under the lock
 * keeps the values stable even if the helper removes them right after.
 */
ngx_int_t ngx_autocert_alpn_get(ngx_shm_zone_t *shm_zone, ngx_str_t *domain,
    ngx_pool_t *pool, ngx_str_t *cert, ngx_str_t *key);


#endif /* _NGX_AUTOCERT_ALPN_H_INCLUDED_ */
